OrdererOrgs:
  - Name: Orderer
    Domain: flashback.local
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.flashback.local
    EnableNodeOUs: true
    Template:
      Count: 1
      Start: 0
    Users:
      Count: 1
