#!/bin/bash

# Kaleido Live Deployment - Complete Steps
# This script provides all the manual steps needed to deploy and test

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     KALEIDO LIVE DEPLOYMENT - MANUAL STEPS                 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ INFRASTRUCTURE READY"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Components built and ready:"
echo "  ✓ CLI Tool (scripts/fabric-cli.ts)"
echo "  ✓ E2E Tests (__tests__/cli-e2e.test.mjs - 40+ tests)"
echo "  ✓ REST Gateway Client (src/lib/kaleido-api.ts)"
echo "  ✓ Configuration (src/lib/kaleido-config.ts)"
echo "  ✓ Chaincode Binary (chaincode/movie/movie-chaincode - 18.5MB)"
echo ""

echo "Kaleido Configuration:"
echo "  REST Gateway: https://u0inmt8fjp-connect.us0-aws-ws.kaleido.io"
echo "  Channel: default-channel"
echo "  Network ID: u0inmt8fjp"
echo "  App ID: u0hjwp2mgt"
echo ""

echo "📋 STEP 1: INSTALL CHAINCODE VIA KALEIDO CONSOLE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Note: The Kaleido REST Gateway requires chaincodes to be"
echo "installed via the Console UI first, then we can test via API."
echo ""
echo "Manual Steps:"
echo "  1. Open Kaleido Console:"
echo "     https://console.kaleido.io"
echo ""
echo "  2. Navigate to your network:"
echo "     Network ID: u0inmt8fjp"
echo ""
echo "  3. Install the chaincode:"
echo "     - Click 'Deploy Chaincode' or similar button"
echo "     - Name: movie"
echo "     - Version: 1.0.0"
echo "     - Upload binary from:"
echo "       /Users/ari.asulin/dev/test/rust2/chaincode/movie/movie-chaincode"
echo "     - Channel: default-channel"
echo "     - Language: Go"
echo "     - Endorsement Policy: OR('Org1MSP.peer')"
echo "     - Save and deploy"
echo ""
echo "  4. Wait for deployment to complete"
echo "     (Usually 30-60 seconds, monitor in console)"
echo ""

echo "🔍 STEP 2: VERIFY DEPLOYMENT"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "After deployment, verify with:"
echo ""
echo "  npm run check:kaleido"
echo ""
echo "Expected output:"
echo "  ✓ movie is deployed"
echo "  ✓ All chaincodes deployed successfully!"
echo ""

echo "🧪 STEP 3: RUN LIVE E2E TESTS"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Once deployment is verified, run the live tests:"
echo ""
echo "CLI E2E Tests:"
echo "  npm run cli:test:live"
echo ""
echo "Expected: All 23 tests pass"
echo ""

echo "🖥️  STEP 4: TEST MANUALLY VIA CLI"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Test individual commands:"
echo ""
echo "  # Check health"
echo "  npm run cli:dev -- health"
echo ""
echo "  # Query all movies"
echo "  npm run cli:dev -- query-all"
echo ""
echo "  # Query with table format"
echo "  npm run cli:dev -- query-all --format table"
echo ""
echo "  # Search by title"
echo "  npm run cli:dev -- search-title 'Inception'"
echo ""
echo "  # Get help"
echo "  npm run cli:dev -- --help"
echo ""

echo "📊 TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "If deployment fails:"
echo ""
echo "  1. Check Kaleido Console for errors"
echo "  2. Verify network and channel exist"
echo "  3. Try deploying chaincode again"
echo "  4. Check that Go modules are valid in chaincode directory"
echo ""

echo "If tests timeout:"
echo ""
echo "  1. Verify chaincode is instantiated (not just installed)"
echo "  2. Check network connectivity"
echo "  3. Verify REST Gateway is accessible:"
echo "     npm run check:kaleido"
echo ""

echo "If CLI returns errors:"
echo ""
echo "  1. Check .env.local has correct credentials"
echo "  2. Verify REST Gateway URL is accessible"
echo "  3. Ensure chaincode is deployed and running"
echo ""

echo "🎉 SUCCESS CRITERIA"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "You'll know everything is working when:"
echo ""
echo "  ✓ npm run check:kaleido shows all chaincodes deployed"
echo "  ✓ npm run cli:test:live passes all 23 tests"
echo "  ✓ npm run cli:dev -- query-all returns data"
echo "  ✓ REST Gateway responds with transaction IDs"
echo ""

echo "📝 MONITORING"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Monitor your deployment:"
echo ""
echo "  • Kaleido Console: https://console.kaleido.io"
echo "  • Network: u0inmt8fjp"
echo "  • Channel: default-channel"
echo "  • Chaincode: movie v1.0.0"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""
echo "Ready to deploy? Follow the manual steps above."
echo "After console deployment, verify with: npm run check:kaleido"
echo ""
