version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rust-tcp-server
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  client1:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs-client-1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - SERVER_URL=http://server:8080
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

  client2:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs-client-2
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - SERVER_URL=http://server:8080
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
