[server]
# Port to bind to (will try next ports if in use)
port = 8080

# Heartbeat interval in seconds
# Server expects a ping from clients within this interval
heartbeat_interval = 60

# Connection timeout in seconds
# If no message received within this time, disconnect the client
connection_timeout = 120

[network]
# Host to bind to (0.0.0.0 for all interfaces)
host = "0.0.0.0"

# Maximum number of concurrent clients
max_clients = 100
