# Flashback Server configuration example
# Copy this file to config.toml and adjust as needed.

[server]
# The single canonical port used by the server. Clients should connect to this port.
# Default if not set: 51111
port = 51111

# How often clients are expected to ping (seconds)
heartbeat_interval = 60

# Disconnect clients that haven't pinged in this many seconds
connection_timeout = 120

# Listen host
host = "0.0.0.0"

# Maximum number of concurrent clients
max_clients = 100
