name: Build and Test Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - 'client/**'
      - '.github/workflows/deploy-server.yml'
  workflow_dispatch:

permissions:
  contents: read

env:
  RUST_BACKTRACE: 1
  SERVER_PORT: 51111

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            server
            client/src-tauri

      - name: Build server
        working-directory: server
        run: cargo build --release

      - name: Run server tests
        working-directory: server
        run: cargo test --release

      - name: Build client
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Run client tests
        working-directory: client
        run: npm run test || true

      - name: Build client binary
        working-directory: client
        run: npm run tauri:build || true
